set(ARILES_CPP_STANDARD         "c++11" CACHE STRING "")
set(ARILES_CPP_SANITIZERS       "ON"    CACHE STRING "")

set(ARILES_VISITOR_graphviz     "ON"    CACHE STRING "")
set(ARILES_VISITOR_pugixml      "ON"    CACHE STRING "")
set(ARILES_VISITOR_rapidjson    "ON"    CACHE STRING "")
set(ARILES_VISITOR_jsonnet      "ON"    CACHE STRING "")
set(ARILES_VISITOR_msgpack      "ON"    CACHE STRING "")
set(ARILES_VISITOR_yaml_cpp     "ON"    CACHE STRING "")
set(ARILES_VISITOR_rosparam     "OFF"   CACHE STRING "")
