language: cpp

compiler:
    - clang
    - gcc

os: linux

addons:
    apt:
        packages:
            - libboost-all-dev
            - libeigen3-dev
            - octave

notifications:
    email:
        on_success: always
        on_failure: always


script: make build-tests TYPE=Debug OPTIONS=cpp03_build_noros TARGETS="all"
