language: cpp

compiler:
    - clang
#    - gcc

os: linux

addons:
    apt:
        packages:
            - libboost-all-dev
            - libeigen3-dev
            - octave

script: make build-tests TYPE=Debug OPTIONS=cpp03_build_noros TARGETS="all" EXTRA_CMAKE_PARAM="-DARILES_ADAPTER_BOOST_POINTER=OFF"
