language: cpp

notifications:
    email:
        recipients:
            - asherikov@yandex.com
        on_success: always
        on_failure: always

jobs:
    include:

# special cases
    # no core
      - os: linux
        dist: trusty
        compiler: clang
        script:
          - make build TYPE=Debug OPTIONS=no_core TARGETS="all"
        addons:
            apt:
                update: true
                packages:
                  - libboost-all-dev
                  - libeigen3-dev


    # deb packages
      - os: linux
        compiler: clang
        dist: trusty
        sudo: required
        cache:
          - apt

        env:
          - ROS_DISTRO=indigo
          - CI_SOURCE_PATH=$(pwd)
          - ROS_CI_DESKTOP=trusty
          - ROSINSTALL_FILE=$CI_SOURCE_PATH/dependencies.rosinstall
          - CATKIN_OPTIONS=$CI_SOURCE_PATH/catkin.options
          # Set the python path manually to include /usr/-/python2.7/dist-packages
          # as this is where apt-get installs python packages.
          - PYTHONPATH=$PYTHONPATH:/usr/lib/python2.7/dist-packages:/usr/local/lib/python2.7/dist-packages

        # Install system dependencies, namely a very barebones ROS setup.
        before_install:
          - sudo make install-ros ROS_DISTRO=$ROS_DISTRO UBUNTU_DISTRO=$ROS_CI_DESKTOP
          - source /opt/ros/${ROS_DISTRO}/setup.bash
          - rosdep update

        addons:
            apt:
                update: true
                packages:
                  - devscripts
                  - build-essential
                  - libboost-all-dev
                  - libeigen3-dev
                  - octave
                  - libpugixml-dev
                  - libyaml-cpp-dev
                  - fakeroot

        script:
          - make deb-build DEB_TARGET=trusty
          - make deb-install DEB_TARGET=trusty
          - make cmake_dependency

# clang

    # From git submodules / C++11
      - os: linux
        dist: trusty
        compiler: clang
        script:
          - make build-tests TYPE=Debug OPTIONS=cpp11_build_noros TARGETS="all" ARGS=-V
        addons:
            apt:
                update: true
                packages:
                  - libboost-all-dev
                  - libeigen3-dev
                  - octave

    # From gitsubmodules / C++03
      - os: linux
        dist: trusty
        compiler: clang
        script:
          - make build-tests TYPE=Debug OPTIONS=cpp03_build_noros TARGETS="all" ARGS=-V
        addons:
            apt:
                update: true
                packages:
                  - libboost-all-dev
                  - libeigen3-dev
                  - octave

    # From packages / C++11
      - os: linux
        dist: trusty
        compiler: clang
        script:
          - make build-tests TYPE=Debug OPTIONS=cpp11_on_noros_trusty TARGETS="all" ARGS=-V
        addons:
            apt:
                update: true
                packages:
                  - libboost-all-dev
                  - libeigen3-dev
                  - octave
                  - libpugixml-dev
                  - libyaml-cpp-dev
                 #- rapidjson-dev       # not found
                 #- libmsgpack-dev      # version is too old


    # ROS / C++11
    # based on https://github.com/felixduvallet/ros-travis-integration/blob/master/.travis.yml
      - os: linux
        compiler: clang
        dist: trusty
        sudo: required
        cache:
          - apt

        env:
          - ROS_DISTRO=indigo
          - CI_SOURCE_PATH=$(pwd)
          - ROS_CI_DESKTOP=trusty
          - ROSINSTALL_FILE=$CI_SOURCE_PATH/dependencies.rosinstall
          - CATKIN_OPTIONS=$CI_SOURCE_PATH/catkin.options
          # Set the python path manually to include /usr/-/python2.7/dist-packages
          # as this is where apt-get installs python packages.
          - PYTHONPATH=$PYTHONPATH:/usr/lib/python2.7/dist-packages:/usr/local/lib/python2.7/dist-packages

        # Install system dependencies, namely a very barebones ROS setup.
        before_install:
          - sudo make install-ros ROS_DISTRO=$ROS_DISTRO UBUNTU_DISTRO=$ROS_CI_DESKTOP
          - source /opt/ros/${ROS_DISTRO}/setup.bash
          - rosdep update

        addons:
            apt:
                update: true
                packages:
                  - libboost-all-dev
                  - libeigen3-dev
                  - octave

        script:
          - make build-tests TYPE=Debug OPTIONS=ros TARGETS="all" ARGS=-V


# GCC

    # From git submodules / C++11
      - os: linux
        dist: trusty
        compiler: gcc
        script:
          - make build-tests TYPE=Debug OPTIONS=cpp11_build_noros TARGETS="all" ARGS=-V
        addons:
            apt:
                update: true
                packages:
                  - libboost-all-dev
                  - libeigen3-dev
                  - octave

    # From gitsubmodules / C++03
      - os: linux
        dist: trusty
        compiler: gcc
        script:
          - make build-tests TYPE=Debug OPTIONS=cpp03_build_noros TARGETS="all" ARGS=-V
        addons:
            apt:
                update: true
                packages:
                  - libboost-all-dev
                  - libeigen3-dev
                  - octave

    # From packages / C++11
      - os: linux
        dist: trusty
        compiler: gcc
        script:
          - make build-tests TYPE=Debug OPTIONS=cpp11_on_noros_trusty TARGETS="all" ARGS=-V
        addons:
            apt:
                update: true
                packages:
                  - libboost-all-dev
                  - libeigen3-dev
                  - octave
                  - libpugixml-dev
                  - libyaml-cpp-dev
                 #- rapidjson-dev       # not found
                 #- libmsgpack-dev      # version is too old


    # ROS / C++11
    # based on https://github.com/felixduvallet/ros-travis-integration/blob/master/.travis.yml
      - os: linux
        compiler: gcc
        dist: trusty
        sudo: required
        cache:
          - apt

        env:
          - ROS_DISTRO=indigo
          - CI_SOURCE_PATH=$(pwd)
          - ROS_CI_DESKTOP=trusty
          - ROSINSTALL_FILE=$CI_SOURCE_PATH/dependencies.rosinstall
          - CATKIN_OPTIONS=$CI_SOURCE_PATH/catkin.options
          # Set the python path manually to include /usr/-/python2.7/dist-packages
          # as this is where apt-get installs python packages.
          - PYTHONPATH=$PYTHONPATH:/usr/lib/python2.7/dist-packages:/usr/local/lib/python2.7/dist-packages

        # Install system dependencies, namely a very barebones ROS setup.
        before_install:
          - sudo make install-ros ROS_DISTRO=$ROS_DISTRO UBUNTU_DISTRO=$ROS_CI_DESKTOP
          - source /opt/ros/${ROS_DISTRO}/setup.bash
          - rosdep update

        addons:
            apt:
                update: true
                packages:
                  - libboost-all-dev
                  - libeigen3-dev
                  - octave

        script:
          - make build-tests TYPE=Debug OPTIONS=ros TARGETS="all" ARGS=-V

