language: cpp

notifications:
    email:
        recipients:
            - asherikov@yandex.com
        on_success: always
        on_failure: always

services:
  - docker
os: linux
dist: trusty

jobs:
    include:

    # melodic / 18.04
      - script:
          - make ros_make_docker ROS_DISTRO=melodic UBUNTU_DISTRO=bionic BRANCH=${TRAVIS_BRANCH} TARGET=catkin_test_old
      - script:
          - make ros_make_docker ROS_DISTRO=melodic UBUNTU_DISTRO=bionic BRANCH=${TRAVIS_BRANCH} TARGET=catkin_test_new

    # kinetic / 16.04
      - script:
          - make ros_make_docker ROS_DISTRO=kinetic UBUNTU_DISTRO=xenial BRANCH=${TRAVIS_BRANCH} TARGET=catkin_test_old
      - script:
          - make ros_make_docker ROS_DISTRO=kinetic UBUNTU_DISTRO=xenial BRANCH=${TRAVIS_BRANCH} TARGET=catkin_test_new

    # prerelease
      - sudo: required
        script:
          - make ros_prerelease ROS_DISTRO=melodic UBUNTU_DISTRO=bionic BRANCH=${TRAVIS_BRANCH}
