language: cpp

notifications:
    email:
        recipients:
            - asherikov@yandex.com
        on_success: always
        on_failure: always

services:
  - docker
os: linux
dist: trusty

jobs:
    include:

    # melodic / 18.04
      - script:
          - make make-docker ROS_DISTRO=melodic UBUNTU_DISTRO=bionic BRANCH=${TRAVIS_BRANCH} TARGET=catkin-test-old
      - script:
          - make make-docker ROS_DISTRO=melodic UBUNTU_DISTRO=bionic BRANCH=${TRAVIS_BRANCH} TARGET=catkin-test-new

    # kinetic / 16.04
      - script:
          - make make-docker ROS_DISTRO=kinetic UBUNTU_DISTRO=xenial BRANCH=${TRAVIS_BRANCH} TARGET=catkin-test-old
      - script:
          - make make-docker ROS_DISTRO=kinetic UBUNTU_DISTRO=xenial BRANCH=${TRAVIS_BRANCH} TARGET=catkin-test-new

    # prerelease
    #  - sudo: required
    #    script:
    #      - make ros-prerelease TRAVIS_UBUNTU_DISTRO=trusty ROS_DISTRO=melodic UBUNTU_DISTRO=bionic BRANCH=${TRAVIS_BRANCH}
