language: cpp

notifications:
    email:
        recipients:
            - asherikov@yandex.com
        on_success: always
        on_failure: always

services:
  - docker
os: linux
dist: trusty

jobs:
    include:

    # melodic / 18.04
      - script:
          - make make-docker ROS_DISTRO=melodic DOCKER_IMAGE=ros:melodic-ros-base-bionic BRANCH=${TRAVIS_BRANCH} TARGET=catkin-build-old
