set(ARILES_BRIDGE_jsonnet       "OFF"   CACHE STRING "")
set(ARILES_BRIDGE_pugixml       "BUILD" CACHE STRING "")
set(ARILES_BRIDGE_rapidjson     "BUILD" CACHE STRING "")
set(ARILES_BRIDGE_msgpack       "BUILD" CACHE STRING "")
set(ARILES_BRIDGE_yaml_cpp03    "BUILD" CACHE STRING "")
set(ARILES_BRIDGE_yaml_cpp      "OFF"   CACHE STRING "")
set(ARILES_BRIDGE_ros           "OFF"   CACHE STRING "")
