set(ARILES_ENABLE_CORE          "OFF" CACHE STRING "")

set(ARILES_CPP_STANDARD         "c++11" CACHE STRING "")

set(ARILES_BRIDGES_DEFAULT_MODE "OFF"   CACHE STRING "")
set(ARILES_BRIDGE_octave        "ON"   CACHE STRING "")
