set(ARILES_ENABLE_CORE          "NOINSTALL" CACHE STRING "")

set(ARILES_CPP_STANDARD         "c++11" CACHE STRING "")

set(ARILES_VISITORS_DEFAULT_MODE    "OFF"   CACHE STRING "")
set(ARILES_VISITOR_namevalue        "ON"   CACHE STRING "")
