set(ARILES_BRIDGE_pugixml       "ON"    CACHE STRING "")
set(ARILES_BRIDGE_rapidjson     "ON"    CACHE STRING "")
set(ARILES_BRIDGE_jsonnet       "ON"    CACHE STRING "")
set(ARILES_BRIDGE_msgpack       "ON"    CACHE STRING "")
set(ARILES_BRIDGE_yaml_cpp03    "ON"    CACHE STRING "")
set(ARILES_BRIDGE_yaml_cpp      "OFF"   CACHE STRING "")
set(ARILES_BRIDGE_ros           "OFF"   CACHE STRING "")
