on: [push, pull_request]

env:
    APT: sudo apt install -y --no-install-recommends
    # Set the python path manually to include /usr/-/python2.7/dist-packages
    # as this is where apt-get installs python packages.
    ROSINSTALL_FILE: $GITHUB_WORKSPACE/dependencies.rosinstall
    CATKIN_OPTIONS: $GITHUB_WORKSPACE/catkin.options

jobs:
    deb_packages:
        runs-on: ubuntu-16.04

        env:
            ROS_DISTRO: kinetic
            ROS_HOSTNAME: localhost
            ROS_CI_DESKTOP: xenial
            PYTHONPATH: $PYTHONPATH:/usr/lib/python2.7/dist-packages:/usr/local/lib/python2.7/dist-packages

        # Install system dependencies, namely a very barebones ROS setup.
        steps:
            - uses: actions/checkout@v2
            - run: sudo make install-ros ROS_DISTRO=$ROS_DISTRO UBUNTU_DISTRO=$ROS_CI_DESKTOP
            - run: rosdep update
            - run: $APT cmake libboost-all-dev libeigen3-dev
            - run: $APT devscripts build-essential octave libpugixml-dev libyaml-cpp-dev fakeroot rapidjson-dev
            - run: $APT libprotobuf-dev protobuf-compiler
            - run: sudo make install-jsonnet
            - run: |
                source /opt/ros/$ROS_DISTRO/setup.bash
                make deb-build DEB_TARGET=xenial
                make deb-install DEB_TARGET=xenial
                make cmake_dependency


    bionic_deb_packages:
        runs-on: ubuntu-18.04

        env:
            ROS_DISTRO: melodic
            ROS_HOSTNAME: localhost
            ROS_CI_DESKTOP: bionic
            PYTHONPATH: $PYTHONPATH:/usr/lib/python2.7/dist-packages:/usr/local/lib/python2.7/dist-packages

        # Install system dependencies, namely a very barebones ROS setup.
        steps:
            - uses: actions/checkout@v2
            - run: sudo make install-ros ROS_DISTRO=$ROS_DISTRO UBUNTU_DISTRO=$ROS_CI_DESKTOP
            - run: rosdep update
            - run: $APT cmake libboost-all-dev libeigen3-dev
            - run: $APT devscripts build-essential octave libpugixml-dev libyaml-cpp-dev fakeroot rapidjson-dev libmsgpack-dev
            - run: $APT libprotobuf-dev protobuf-compiler
            - run: sudo make install-jsonnet
            - run: |
                source /opt/ros/$ROS_DISTRO/setup.bash
                make deb-build DEB_TARGET=bionic
                make deb-install DEB_TARGET=bionic
                make cmake_dependency


    xenial_gcc_cpp11_noros:
        runs-on: ubuntu-16.04
        steps:
            - uses: actions/checkout@v2
            - run: sudo apt update
            - run: $APT cmake libboost-all-dev libeigen3-dev
            - run: $APT octave libpugixml-dev libyaml-cpp-dev rapidjson-dev libmsgpack-dev graphviz
            - run: $APT libprotobuf-dev protobuf-compiler
            - run: sudo make install-jsonnet
            - run: make build-tests TYPE=Debug OPTIONS=cpp11_on_noros_xenial TARGETS="all" TC=gcc ARGS=-V


    xenial_clang_cpp11_noros:
        runs-on: ubuntu-16.04
        steps:
            - uses: actions/checkout@v2
            - run: sudo apt update
            - run: $APT cmake libboost-all-dev libeigen3-dev
            - run: $APT octave libpugixml-dev libyaml-cpp-dev rapidjson-dev libmsgpack-dev graphviz
            - run: $APT libprotobuf-dev protobuf-compiler
            - run: sudo make install-jsonnet
            - run: make build-tests TYPE=Debug OPTIONS=cpp11_on_noros_xenial TARGETS="all" TC=clang ARGS=-V


    bionic_gcc_cpp11_noros:
        runs-on: ubuntu-18.04
        steps:
            - uses: actions/checkout@v2
            - run: sudo apt update
            - run: $APT cmake libboost-all-dev libeigen3-dev
            - run: $APT octave libpugixml-dev libyaml-cpp-dev rapidjson-dev libmsgpack-dev graphviz
            - run: $APT libprotobuf-dev protobuf-compiler
            - run: sudo make install-jsonnet
            - run: make build-tests TYPE=Debug OPTIONS=cpp11_on_noros_bionic TARGETS="all" TC=gcc ARGS=-V


    gcc_cpp11_ros:
        runs-on: ubuntu-16.04

        env:
            ROS_DISTRO: kinetic
            ROS_HOSTNAME: localhost
            ROS_CI_DESKTOP: xenial
            PYTHONPATH: $PYTHONPATH:/usr/lib/python2.7/dist-packages:/usr/local/lib/python2.7/dist-packages

        # Install system dependencies, namely a very barebones ROS setup.
        steps:
            - uses: actions/checkout@v2
            - run: sudo make install-ros ROS_DISTRO=$ROS_DISTRO UBUNTU_DISTRO=$ROS_CI_DESKTOP
            - run: rosdep update
            - run: $APT cmake libboost-all-dev libeigen3-dev
            - run: $APT libyaml-cpp-dev octave graphviz
            - run: $APT libprotobuf-dev protobuf-compiler
            - run: sudo make install-jsonnet
            - run: |
                source /opt/ros/$ROS_DISTRO/setup.bash
                make build-tests TYPE=Debug OPTIONS=ros TARGETS="all" TC=gcc ARGS=-V


    clang_cpp11_ros:
        runs-on: ubuntu-16.04

        env:
            ROS_DISTRO: kinetic
            ROS_HOSTNAME: localhost
            ROS_CI_DESKTOP: xenial
            PYTHONPATH: $PYTHONPATH:/usr/lib/python2.7/dist-packages:/usr/local/lib/python2.7/dist-packages

        # Install system dependencies, namely a very barebones ROS setup.
        steps:
            - uses: actions/checkout@v2
            - run: sudo make install-ros ROS_DISTRO=$ROS_DISTRO UBUNTU_DISTRO=$ROS_CI_DESKTOP
            - run: rosdep update
            - run: sudo $APT cmake libboost-all-dev libeigen3-dev
            - run: sudo $APT libyaml-cpp-dev octave graphviz
            - run: sudo $APT libprotobuf-dev protobuf-compiler
            - run: sudo make install-jsonnet
            - run: |
                source /opt/ros/$ROS_DISTRO/setup.bash
                make build-tests TYPE=Debug OPTIONS=ros TARGETS="all" TC=clang ARGS=-V


    bionic_gcc_cpp11_ros:
        runs-on: ubuntu-18.04

        env:
            ROS_DISTRO: melodic
            ROS_HOSTNAME: localhost
            ROS_CI_DESKTOP: bionic
            PYTHONPATH: $PYTHONPATH:/usr/lib/python2.7/dist-packages:/usr/local/lib/python2.7/dist-packages

        # Install system dependencies, namely a very barebones ROS setup.
        steps:
            - uses: actions/checkout@v2
            - run: sudo make install-ros ROS_DISTRO=$ROS_DISTRO UBUNTU_DISTRO=$ROS_CI_DESKTOP
            - run: rosdep update
            - run: $APT cmake libboost-all-dev libeigen3-dev
            - run: $APT libyaml-cpp-dev octave graphviz
            - run: $APT libprotobuf-dev protobuf-compiler
            - run: sudo make install-jsonnet
            - run: |
                source /opt/ros/$ROS_DISTRO/setup.bash
                make build-tests TYPE=Debug OPTIONS=ros TARGETS="all" TC=gcc ARGS=-V


    bionic_static_checks:
        runs-on: ubuntu-18.04

        steps:
            - uses: actions/checkout@v2
            - run: sudo apt update
            - run: sudo apt upgrade
            - run: $APT cppcheck
            - run: $APT python3-pip python3-setuptools
            - run: sudo pip3 install scspell3k
            - run: make cppcheck
            - run: make spell


    bionic_gcc_cpp11_ros_scanbuild:
        runs-on: ubuntu-18.04

        env:
            ROS_DISTRO: melodic
            ROS_HOSTNAME: localhost
            ROS_CI_DESKTOP: bionic
            PYTHONPATH: $PYTHONPATH:/usr/lib/python2.7/dist-packages:/usr/local/lib/python2.7/dist-packages

        # Install system dependencies, namely a very barebones ROS setup.
        steps:
            - uses: actions/checkout@v2
            - run: sudo make install-ros ROS_DISTRO=$ROS_DISTRO UBUNTU_DISTRO=$ROS_CI_DESKTOP
            - run: rosdep update
            - run: $APT cmake libboost-all-dev libeigen3-dev
            - run: $APT libyaml-cpp-dev octave
            - run: $APT clang-tools-9 clang-tidy-9
            - run: $APT libprotobuf-dev protobuf-compiler
            - run: sudo make install-jsonnet
            - run: |
                source /opt/ros/$ROS_DISTRO/setup.bash
                make clangcheck SCANBUILD=scan-build-9 OPTIONS=ros_tidy TC=gcc
