on: [push, pull_request]

defaults:
    run:
        shell: bash

jobs:
    # focal
    focal_noetic_catkin_old:
        container: ros:noetic-ros-base-focal
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v3
            - run: |
                source /opt/ros/noetic/setup.bash
                make catkin_test_old ROS_DISTRO=noetic UBUNTU_DISTRO=focal

    focal_noetic_catkin_new:
        container: ros:noetic-ros-base-focal
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v3
            - run: |
                source /opt/ros/noetic/setup.bash
                make catkin_test_new ROS_DISTRO=noetic UBUNTU_DISTRO=focal

    prerelease:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - run: make ros_prerelease ROS_DISTRO=noetic UBUNTU_DISTRO=focal BRANCH=`git branch --show-current`
              env:
                  CCACHE_DIR: ${GITHUB_WORKSPACE}/.ccache
