on: [push, pull_request]

defaults:
    run:
        shell: bash

jobs:
    # focal
    focal_noetic_catkin_old:
        container: ros:noetic-ros-base-focal
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: |
                source /opt/ros/noetic/setup.bash
                make catkin_test_old ROS_DISTRO=noetic UBUNTU_DISTRO=focal

    focal_noetic_catkin_new:
        container: ros:noetic-ros-base-focal
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: |
                source /opt/ros/noetic/setup.bash
                make catkin_test_new ROS_DISTRO=noetic UBUNTU_DISTRO=focal


    # bionic
    bionic_melodic_catkin_old:
        container: ros:melodic-ros-base-bionic
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: |
                source /opt/ros/melodic/setup.bash
                make catkin_test_old ROS_DISTRO=melodic UBUNTU_DISTRO=bionic

    bionic_melodic_catkin_new:
        container: ros:melodic-ros-base-bionic
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: |
                source /opt/ros/melodic/setup.bash
                make catkin_test_new ROS_DISTRO=melodic UBUNTU_DISTRO=bionic


    prerelease:
        runs-on: ubuntu-18.04
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - run: make ros_prerelease ROS_DISTRO=melodic UBUNTU_DISTRO=bionic BRANCH=`git branch --show-current`
              env:
                  CCACHE_DIR: ${GITHUB_WORKSPACE}/.ccache
