on: [push, pull_request]

env:
    APT: sudo apt install -y --no-install-recommends
    # Set the python path manually to include /usr/-/python2.7/dist-packages
    # as this is where apt-get installs python packages.
    ROSINSTALL_FILE: $GITHUB_WORKSPACE/dependencies.rosinstall
    CATKIN_OPTIONS: $GITHUB_WORKSPACE/catkin.options

jobs:
    bionic_deb_packages:
        runs-on: ubuntu-18.04

        env:
            ROS_DISTRO: melodic
            ROS_HOSTNAME: localhost
            ROS_CI_DESKTOP: bionic
            PYTHONPATH: $PYTHONPATH:/usr/lib/python2.7/dist-packages:/usr/local/lib/python2.7/dist-packages

        # Install system dependencies, namely a very barebones ROS setup.
        steps:
            - uses: actions/checkout@v2
            - run: sudo make install-ros ROS_DISTRO=$ROS_DISTRO UBUNTU_DISTRO=$ROS_CI_DESKTOP
            - run: rosdep update
            - run: sudo make install-deps
            - run: sudo make install-jsonnet
            - run: $APT fakeroot devscripts build-essential
            - run: |
                source /opt/ros/$ROS_DISTRO/setup.bash
                make deb-build DEB_TARGET=bionic
                make deb-install DEB_TARGET=bionic
                make cmake_dependency


    focal_deb_packages:
        runs-on: ubuntu-20.04

        env:
            ROS_DISTRO: noetic
            ROS_HOSTNAME: localhost
            ROS_CI_DESKTOP: focal
            PYTHONPATH: $PYTHONPATH:/usr/lib/python2.7/dist-packages:/usr/local/lib/python2.7/dist-packages

        # Install system dependencies, namely a very barebones ROS setup.
        steps:
            - uses: actions/checkout@v2
            - run: sudo make install-ros ROS_DISTRO=$ROS_DISTRO UBUNTU_DISTRO=$ROS_CI_DESKTOP
            - run: rosdep update
            - run: sudo make install-deps
            - run: sudo make install-jsonnet
            - run: $APT fakeroot devscripts build-essential
            - run: |
                source /opt/ros/$ROS_DISTRO/setup.bash
                make deb-build DEB_TARGET=focal
                make deb-install DEB_TARGET=focal
                make cmake_dependency


    bionic_clang_noros:
        runs-on: ubuntu-18.04
        steps:
            - uses: actions/checkout@v2
            - run: sudo apt update
            - run: sudo make install-deps
            - run: sudo make install-jsonnet
            - run: make build-tests TYPE=Debug OPTIONS=cpp11_on_noros TARGETS="all" TC=clang ARGS=-V


    bionic_gcc_noros:
        runs-on: ubuntu-18.04
        steps:
            - uses: actions/checkout@v2
            - run: sudo apt update
            - run: sudo make install-deps
            - run: sudo make install-jsonnet
            - run: make build-tests TYPE=Debug OPTIONS=cpp11_on_noros TARGETS="all" TC=gcc ARGS=-V


    focal_gcc_noros:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2
            - run: sudo apt update
            - run: sudo make install-deps
            - run: sudo make install-jsonnet
            - run: make build-tests TYPE=Debug OPTIONS=cpp11_on_noros TARGETS="all" TC=gcc ARGS=-V


    bionic_gcc_ros:
        runs-on: ubuntu-18.04

        env:
            ROS_DISTRO: melodic
            ROS_HOSTNAME: localhost
            ROS_CI_DESKTOP: bionic
            PYTHONPATH: $PYTHONPATH:/usr/lib/python2.7/dist-packages:/usr/local/lib/python2.7/dist-packages

        # Install system dependencies, namely a very barebones ROS setup.
        steps:
            - uses: actions/checkout@v2
            - run: sudo make install-ros ROS_DISTRO=$ROS_DISTRO UBUNTU_DISTRO=$ROS_CI_DESKTOP
            - run: rosdep update
            - run: sudo make install-deps
            - run: sudo make install-jsonnet
            - run: |
                source /opt/ros/$ROS_DISTRO/setup.bash
                make build-tests TYPE=Debug OPTIONS=ros TARGETS="all" TC=gcc ARGS=-V


    bionic_clang_ros:
        runs-on: ubuntu-18.04

        env:
            ROS_DISTRO: melodic
            ROS_HOSTNAME: localhost
            ROS_CI_DESKTOP: bionic
            PYTHONPATH: $PYTHONPATH:/usr/lib/python2.7/dist-packages:/usr/local/lib/python2.7/dist-packages

        # Install system dependencies, namely a very barebones ROS setup.
        steps:
            - uses: actions/checkout@v2
            - run: sudo make install-ros ROS_DISTRO=$ROS_DISTRO UBUNTU_DISTRO=$ROS_CI_DESKTOP
            - run: rosdep update
            - run: sudo make install-deps
            - run: sudo make install-jsonnet
            - run: |
                source /opt/ros/$ROS_DISTRO/setup.bash
                make build-tests TYPE=Debug OPTIONS=ros TARGETS="all" TC=clang ARGS=-V


    focal_gcc_ros:
        runs-on: ubuntu-20.04

        env:
            ROS_DISTRO: noetic
            ROS_HOSTNAME: localhost
            ROS_CI_DESKTOP: focal
            PYTHONPATH: $PYTHONPATH:/usr/lib/python2.7/dist-packages:/usr/local/lib/python2.7/dist-packages

        # Install system dependencies, namely a very barebones ROS setup.
        steps:
            - uses: actions/checkout@v2
            - run: sudo make install-ros ROS_DISTRO=$ROS_DISTRO UBUNTU_DISTRO=$ROS_CI_DESKTOP
            - run: rosdep update
            - run: sudo make install-deps
            - run: sudo make install-jsonnet
            - run: |
                source /opt/ros/$ROS_DISTRO/setup.bash
                make build-tests TYPE=Debug OPTIONS=ros TARGETS="all" TC=gcc ARGS=-V


    bionic_static_checks:
        runs-on: ubuntu-18.04

        steps:
            - uses: actions/checkout@v2
            - run: sudo apt update
            - run: sudo apt upgrade
            - run: $APT cppcheck
            - run: $APT python3-pip python3-setuptools
            - run: sudo pip3 install scspell3k
            - run: make cppcheck
            - run: make spell


    bionic_gcc_ros_scanbuild:
        runs-on: ubuntu-18.04

        env:
            ROS_DISTRO: melodic
            ROS_HOSTNAME: localhost
            ROS_CI_DESKTOP: bionic
            PYTHONPATH: $PYTHONPATH:/usr/lib/python2.7/dist-packages:/usr/local/lib/python2.7/dist-packages

        # Install system dependencies, namely a very barebones ROS setup.
        steps:
            - uses: actions/checkout@v2
            - run: sudo make install-ros ROS_DISTRO=$ROS_DISTRO UBUNTU_DISTRO=$ROS_CI_DESKTOP
            - run: rosdep update
            - run: $APT cmake libboost-all-dev libeigen3-dev
            - run: $APT libyaml-cpp-dev octave
            - run: $APT clang-tools-9 clang-tidy-9
            - run: $APT libprotobuf-dev protobuf-compiler
            - run: sudo make install-jsonnet
            - run: |
                source /opt/ros/$ROS_DISTRO/setup.bash
                make clangcheck SCANBUILD=scan-build-9 OPTIONS=ros_tidy TC=gcc
