on:
    push:
        branches:
            - '**'
        tags:
            - 'NEVER'
    pull_request:
        types: [opened, reopened]

env:
    APT: sudo apt install -y --no-install-recommends
    # Set the python path manually to include /usr/-/python2.7/dist-packages
    # as this is where apt-get installs python packages.
    ROSINSTALL_FILE: $GITHUB_WORKSPACE/dependencies.rosinstall
    CATKIN_OPTIONS: $GITHUB_WORKSPACE/catkin.options

jobs:
    noble_deb_packages:
        runs-on: ubuntu-22.04

        steps:
            - uses: actions/checkout@v5
            - run: sudo make install-deps
            - run: $APT fakeroot devscripts build-essential
            - run: |
                make deb-build DEB_TARGET=jammy
                make deb-install DEB_TARGET=jammy
                # make cmake_dependency  # requires ROS

    jammy_deb_packages:
        runs-on: ubuntu-22.04

        steps:
            - uses: actions/checkout@v5
            - run: sudo make install-deps
            - run: $APT fakeroot devscripts build-essential
            - run: |
                make deb-build DEB_TARGET=jammy
                make deb-install DEB_TARGET=jammy
                # make cmake_dependency  # requires ROS

    focal_deb_packages:
        container: ros:noetic-ros-base-focal
        runs-on: ubuntu-latest

        env:
            ROS_DISTRO: noetic
            ROS_HOSTNAME: localhost
            ROS_CI_DESKTOP: focal

        steps:
            - uses: actions/checkout@v5
            - run: apt update && apt install -y --no-install-recommends make wget sudo
            - run: rm /etc/ros/rosdep/sources.list.d/20-default.list
            - run: make install-ros ROS_DISTRO=$ROS_DISTRO UBUNTU_DISTRO=$ROS_CI_DESKTOP
            - run: make install-deps
            - run: $APT fakeroot devscripts build-essential
            - shell: bash
              run: |
                source /opt/ros/$ROS_DISTRO/setup.bash
                make deb-build DEB_TARGET=focal
                make deb-install DEB_TARGET=focal
                make cmake_dependency


    noble_gcc_noros:
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@v5
            - run: sudo apt update
            - run: sudo make install-deps
            - run: make build-tests TYPE=Debug OPTIONS=noros TARGETS="all" TC=gcc ARGS=-V

    noble_gcc_ros:
        runs-on: ubuntu-24.04

        env:
            ROS_DISTRO: jazzy
            ROS_CI_DESKTOP: noble

        steps:
            - uses: actions/checkout@v5
            - run: sudo make install-ros ROS_DISTRO=$ROS_DISTRO UBUNTU_DISTRO=$ROS_CI_DESKTOP
            - run: sudo make install-deps
            - run: |
                source /opt/ros/$ROS_DISTRO/setup.bash
                make build-tests TYPE=Debug OPTIONS=ros2 TARGETS="all" TC=gcc ARGS=-V


    jammy_gcc_noros:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v5
            - run: sudo apt update
            - run: sudo make install-deps
            - run: make build-tests TYPE=Debug OPTIONS=noros TARGETS="all" TC=gcc ARGS=-V

    jammy_gcc_ros:
        runs-on: ubuntu-22.04

        env:
            ROS_DISTRO: humble
            ROS_CI_DESKTOP: jammy

        steps:
            - uses: actions/checkout@v5
            - run: sudo make install-ros ROS_DISTRO=$ROS_DISTRO UBUNTU_DISTRO=$ROS_CI_DESKTOP
            - run: sudo make install-deps
            - run: |
                source /opt/ros/$ROS_DISTRO/setup.bash
                make build-tests TYPE=Debug OPTIONS=ros2 TARGETS="all" TC=gcc ARGS=-V


    focal_gcc_noros:
        container: ros:noetic-ros-base-focal
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - run: rm /etc/ros/rosdep/sources.list.d/20-default.list
            - run: apt update && apt install -y --no-install-recommends make wget sudo
            - run: make install-deps
            - run: make build-tests TYPE=Debug OPTIONS=noros_focal TARGETS="all" TC=gcc ARGS=-V

    focal_gcc_ros:
        container: ros:noetic-ros-base-focal
        runs-on: ubuntu-latest

        env:
            ROS_DISTRO: noetic
            ROS_HOSTNAME: localhost
            ROS_CI_DESKTOP: focal

        steps:
            - uses: actions/checkout@v5
            - run: rm /etc/ros/rosdep/sources.list.d/20-default.list
            - run: apt update && apt install -y --no-install-recommends make wget sudo
            - run: make install-ros ROS_DISTRO=$ROS_DISTRO UBUNTU_DISTRO=$ROS_CI_DESKTOP
            - run: make install-deps
            - shell: bash
              run: |
                source /opt/ros/$ROS_DISTRO/setup.bash
                make build-tests TYPE=Debug OPTIONS=ros TARGETS="all" TC=gcc ARGS=-V


    jammy_spelling:
        runs-on: ubuntu-22.04

        steps:
            - uses: actions/checkout@v5
            - run: sudo apt update
            - run: $APT python3-pip python3-setuptools
            - run: sudo pip3 install scspell3k
            - run: make spell


    noble_clang_ros_scanbuild:
        runs-on: ubuntu-24.04

        env:
            ROS_DISTRO: jazzy
            ROS_CI_DESKTOP: noble

        steps:
            - uses: actions/checkout@v5
            - run: sudo make install-ros ROS_DISTRO=$ROS_DISTRO UBUNTU_DISTRO=$ROS_CI_DESKTOP
            - run: sudo make install-deps
            - run: $APT clang-tools-20 clang-tidy-20
            - run: |
                source /opt/ros/$ROS_DISTRO/setup.bash
                make clangcheck SCANBUILD=scan-build-20 OPTIONS=ros2_tidy TC=clang


    noble_clang_noros_scanbuild:
        runs-on: ubuntu-24.04

        steps:
            - uses: actions/checkout@v5
            - run: sudo apt update
            - run: sudo make install-deps
            - run: $APT clang-tools-20 clang-tidy-20
            - run: make clangcheck SCANBUILD=scan-build-20 OPTIONS=noros_tidy TC=clang


    jammy_ccws:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v5
              with:
                repository: asherikov/ccws
            - uses: actions/checkout@v5
              with:
                ref: pkg_ws_2
                path: src/ariles_ws
            - run: cd src/ariles_ws; make update VERSION=${GITHUB_SHA}; rm -Rf ariles2_rosparam_ws demo
            - run: make bp_install_build BUILD_PROFILE=static_checks
            - run: make BUILD_PROFILE=static_checks
            - run: make bp_install_build BUILD_PROFILE=scan_build
            - run: make dep_install PKG=ariles2_core_ws
            - run: make dep_install PKG=ariles2_graphviz_ws
            - run: make dep_install PKG=ariles2_namevalue2_ws
            - run: make dep_install PKG=ariles2_octave_ws
            - run: make dep_install PKG=ariles2_pugixml_ws
            - run: make dep_install PKG=ariles2_rapidjson_ws
            - run: make dep_install PKG=ariles2_ros2param_ws
            - run: make dep_install PKG=ariles2_yamlcpp_ws
            - run: make _ws BUILD_PROFILE=scan_build
            - run: make bp_install_build BUILD_PROFILE=cppcheck
            - run: make BUILD_PROFILE=static_checks BASE_BUILD_PROFILE=scan_build

    noble_ccws:
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@v5
              with:
                repository: asherikov/ccws
            - uses: actions/checkout@v5
              with:
                ref: pkg_ws_2
                path: src/ariles_ws
            - run: cd src/ariles_ws; make update VERSION=${GITHUB_SHA}; rm -Rf ariles2_rosparam_ws demo
            - run: make bp_install_build BUILD_PROFILE=static_checks
            - run: make BUILD_PROFILE=static_checks
            - run: make bp_install_build BUILD_PROFILE=scan_build
            - run: make dep_install PKG=ariles2_core_ws
            - run: make dep_install PKG=ariles2_graphviz_ws
            - run: make dep_install PKG=ariles2_namevalue2_ws
            - run: make dep_install PKG=ariles2_octave_ws
            - run: make dep_install PKG=ariles2_pugixml_ws
            - run: make dep_install PKG=ariles2_rapidjson_ws
            - run: make dep_install PKG=ariles2_ros2param_ws
            - run: make dep_install PKG=ariles2_yamlcpp_ws
            # disable due to https://github.com/Tencent/rapidjson/issues/2347
            - run: touch src/ariles_ws/ariles2_rapidjson_ws/COLCON_IGNORE
            - run: make _ws BUILD_PROFILE=scan_build
            - run: make bp_install_build BUILD_PROFILE=cppcheck
            - run: make BUILD_PROFILE=static_checks BASE_BUILD_PROFILE=scan_build
