on:
    push:
        tags:
            - 2.**

env:
    APT: sudo apt install -y --no-install-recommends
    # Set the python path manually to include /usr/-/python2.7/dist-packages
    # as this is where apt-get installs python packages.
    ROSINSTALL_FILE: $GITHUB_WORKSPACE/dependencies.rosinstall
    CATKIN_OPTIONS: $GITHUB_WORKSPACE/catkin.options

jobs:
    jammy_deb_packages_cloudsmith:
        runs-on: ubuntu-22.04

        env:
            DEB_TARGET: jammy

        steps:
            - uses: actions/checkout@v3
            - run: sudo make install-deps
            - run: $APT fakeroot devscripts build-essential
            - run: make deb-build DEB_TARGET=$DEB_TARGET
            - run: pip install --upgrade cloudsmith-cli
            - run: env CLOUDSMITH_API_KEY=${{ secrets.CLOUDSMITH_API_KEY }} make deb-cloudsmith DEB_TARGET=$DEB_TARGET


    focal_deb_packages_cloudsmith:
        runs-on: ubuntu-20.04

        env:
            ROS_DISTRO: noetic
            ROS_HOSTNAME: localhost
            ROS_CI_DESKTOP: focal
            DEB_TARGET: focal

        steps:
            - uses: actions/checkout@v3
            - run: sudo make install-ros ROS_DISTRO=$ROS_DISTRO UBUNTU_DISTRO=$ROS_CI_DESKTOP
            - run: rosdep update
            - run: sudo make install-deps
            - run: $APT fakeroot devscripts build-essential
            - run: |
                source /opt/ros/$ROS_DISTRO/setup.bash
                make deb-build DEB_TARGET=$DEB_TARGET
            - run: pip install --upgrade cloudsmith-cli
            - run: env CLOUDSMITH_API_KEY=${{ secrets.CLOUDSMITH_API_KEY }} make deb-cloudsmith DEB_TARGET=$DEB_TARGET
