on: [push, pull_request]

defaults:
    run:
        shell: bash

jobs:
    # focal
    focal_noetic_catkin_old:
        container: ros:noetic-ros-base-focal
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - run: rm -Rf ariles2_ros2param_ws
            - run: |
                source /opt/ros/noetic/setup.bash
                make catkin_test_old ROS_DISTRO=noetic UBUNTU_DISTRO=focal

    focal_noetic_catkin_new:
        container: ros:noetic-ros-base-focal
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - run: |
                source /opt/ros/noetic/setup.bash
                make catkin_test_new ROS_DISTRO=noetic UBUNTU_DISTRO=focal

    # does not work with ros2param (rclcpp dependency)
    #prerelease:
    #    runs-on: ubuntu-20.04
    #    steps:
    #        - uses: actions/checkout@v5
    #          with:
    #              fetch-depth: 0
    #        - run: make ros_prerelease ROS_DISTRO=noetic UBUNTU_DISTRO=focal BRANCH=`git branch --show-current`
    #          env:
    #              CCACHE_DIR: ${GITHUB_WORKSPACE}/.ccache

    jammy_ccws:
        container: asherikov/ccws_jammy
        runs-on: ubuntu-latest
        env:
            WORKSPACE_SRC: ${GITHUB_WORKSPACE}
        steps:
            - uses: actions/checkout@v5
            - run: rm demo/plain/CATKIN_IGNORE
            - run: |
                cd /ccws
                apt update
                make dep_install
                make ariles2_plain_demo ariles2_ros2param_ws

    noble_ccws:
        container: asherikov/ccws_noble
        runs-on: ubuntu-latest
        env:
            WORKSPACE_SRC: ${GITHUB_WORKSPACE}
        steps:
            - uses: actions/checkout@v5
            - run: rm demo/plain/CATKIN_IGNORE
            - run: |
                cd /ccws
                apt update
                make dep_install
                make ariles2_plain_demo ariles2_ros2param_ws
