on: [push, pull_request]

defaults:
    run:
        shell: bash

jobs:
    # focal
    focal_noetic_catkin_old:
        container: ros:noetic-ros-base-focal
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: rm -Rf ariles2_ros2param_ws
            - run: |
                source /opt/ros/noetic/setup.bash
                make catkin_test_old ROS_DISTRO=noetic UBUNTU_DISTRO=focal

    focal_noetic_catkin_new:
        container: ros:noetic-ros-base-focal
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: |
                source /opt/ros/noetic/setup.bash
                make catkin_test_new ROS_DISTRO=noetic UBUNTU_DISTRO=focal

    # does not work with ros2param (rclcpp dependency)
    #prerelease:
    #    runs-on: ubuntu-20.04
    #    steps:
    #        - uses: actions/checkout@v4
    #          with:
    #              fetch-depth: 0
    #        - run: make ros_prerelease ROS_DISTRO=noetic UBUNTU_DISTRO=focal BRANCH=`git branch --show-current`
    #          env:
    #              CCACHE_DIR: ${GITHUB_WORKSPACE}/.ccache

    jammy_ccws:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v4
              with:
                repository: asherikov/ccws
            - uses: actions/checkout@v4
              with:
                path: src/ariles_ws
            - run: rm src/ariles_ws/demo/plain/CATKIN_IGNORE
            - run: make bp_install_build BUILD_PROFILE=reldebug
            - run: make dep_install PKG=ariles2_plain_demo
            - run: make ariles2_plain_demo
            - run: make dep_install PKG=ariles2_ros2param_ws
            - run: make ariles2_ros2param_ws

    noble_ccws:
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@v4
              with:
                repository: asherikov/ccws
            - uses: actions/checkout@v4
              with:
                path: src/ariles_ws
            - run: rm src/ariles_ws/demo/plain/CATKIN_IGNORE
            - run: make bp_install_build BUILD_PROFILE=reldebug
            - run: make dep_install PKG=ariles2_plain_demo
            - run: make ariles2_plain_demo
            - run: make dep_install PKG=ariles2_ros2param_ws
            - run: make ariles2_ros2param_ws
